In [121]:
import tensorflow as tf
import numpy as np
import torch
import pandas as pd


In [122]:
print(len(tf.config.experimental.list_physical_devices("GPU")))

0


In [123]:
torch.cuda.is_available()

True

In [124]:


# setting device on GPU if available, else CPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)
print()

#Additional Info when using cuda
if device.type == 'cuda':
    print(torch.cuda.get_device_name(0))
    print('Memory Usage:')
    print('Allocated:', round(torch.cuda.memory_allocated(0)/1024**3,1), 'GB')
    print('Cached:   ', round(torch.cuda.memory_reserved(0)/1024**3,1), 'GB')

Using device: cuda

NVIDIA GeForce RTX 3060
Memory Usage:
Allocated: 0.0 GB
Cached:    0.0 GB


In [149]:
df = pd.read_csv("dataset/framingham.csv")
print(len(df))
n=(int)(len(df)*0.1)
df.iloc[:,15].head
print(df.shape)
df=(df-df.min())/(df.max()-df.min())

4238
(4238, 16)


In [150]:
df=df.fillna((df.min()+df.max())/2)


In [151]:
x_train=df.iloc[n:,:15].values
print(x_train.shape)
x_test=df.iloc[:n,:15].values
print(x_test.shape)
y_train=df.iloc[n:,15].values.reshape(1,-1)
y_test=df.iloc[:n,15].values.reshape(1,-1)
print("so luon nguoi nguy co bi benh tim trong trainset:",np.sum(y_train))
print("so luon nguoi nguy co bi benh tim trong testset:",np.sum(y_test))

(3815, 15)
(423, 15)
so luon nguoi nguy co bi benh tim trong trainset: 566.0
so luon nguoi nguy co bi benh tim trong testset: 78.0


In [152]:
print(y_train)

[[0. 0. 1. ... 0. 0. 0.]]


In [153]:
x_train=x_train.T
x_test=x_test.T


In [154]:
print(y_train)

[[0. 0. 1. ... 0. 0. 0.]]


In [155]:
print (x_train)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.68421053 0.15789474 0.5        ... 0.42105263 0.31578947 0.52631579]
 [0.66666667 0.33333333 0.66666667 ... 0.33333333 0.         0.33333333]
 ...
 [0.48570044 0.2057683  0.07901115 ... 0.1565681  0.08773631 0.14372273]
 [0.44444444 0.56565657 0.35353535 ... 0.4040404  0.42424242 0.36363636]
 [0.12711864 0.20621469 0.5        ... 0.1299435  0.5        0.18926554]]


In [156]:
print(x_train.shape)

(15, 3815)


In [182]:
lr=0.01
w=np.zeros((15,1))
b=25
print(n)
for i in range(10000000):
    z_train=np.dot(w.T,x_train)
    #cal z=w*x+b 
    a_train=1/(1+np.exp(-z_train))
    #cal a=sigmoid(z)
    dz_train=(a_train-y_train)
    #cal gradient
    db=np.sum(dz_train)/n
    dw=np.dot(x_train,dz_train.T)/n
    w=w-lr*dw
    b=b-lr*db

423


In [183]:
print(w)
print(b)

[[ 0.24731393]
 [ 0.83972548]
 [-0.63411152]
 [-0.41131135]
 [ 1.59527354]
 [ 0.45475639]
 [ 0.99030558]
 [ 0.78720316]
 [ 1.0564272 ]
 [-3.00144885]
 [ 3.73783686]
 [-3.4206348 ]
 [-2.17943588]
 [-2.25721533]
 [-0.34791721]]
-13754.314115248275


In [184]:
#check result
y_pred=1/(1+np.exp(-(np.dot(w.T,x_test)+b)))

y_pred=np.round(y_pred)
print(y_pred)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

D:\LQH\python\envs\pytorch\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


In [185]:
res=abs(y_test-y_pred)



In [186]:
count =(1-((np.sum(res))/len(res.T)))*100
print("correct prediction:",count,"%")

correct prediction: 81.56028368794325 %
